### ISSUE TITLE
new feature: custom loading 

### ISSUE THREAD

**Issue by shahmirzali49** [gabrielpatricksouza/image_network#1]
first of all, thank you for the package, I really liked it,  Can you add new loading? for example, shimmer or another loading widgets, and also let us use our custom loading widget.

**Comment by gabrielpatricksouza** [comment]
I really appreciate the message, and yes, in the next update I will already put new types of uploads, as well as giving the freedom to use a custom upload, as soon as it will be available

**Comment by gabrielpatricksouza** [comment]
Your request has been granted and is now available in version 2.2.0. Thank you very much for the feedback 👊.
