### ISSUE TITLE
Having ImageNetwork as a child in InkWell, makes the InkWell unclickable.

### ISSUE THREAD

**Issue by nietsmmar** [gabrielpatricksouza/image_network#14]
I am having `ImageNetwork` as a sub-child in an InkWell. When I press on the image the InkWell onTap listener is never called. This is really a problem for me as I need to use it inside an InkWell.

**Comment by gabrielpatricksouza** [comment]
Which inkwell feature do you need to use besides onTap?

**Comment by nietsmmar** [comment]
none, the problem is, that my `ImageNetwork` is deeper in my widget-tree and my `InkWell` is way more at the top. And there I am handling the `onTap` action which applies to multiple child widgets in the tree. So I can't use the `onTap` from the `ImageNetwork`.

**Comment by gabrielpatricksouza** [comment]
I understand, unfortunately so far I have not been able to find solutions to this problem, really if the ```image_network``` is deeper in the widget tree and has an ```inkwell```  or  ```gesture detector``` or  ```any widget``` that contains  ```onTap``` or  ```onPress```, it will not work.
I'm looking for a way to solve this problem, if I get a satisfactory result, I'll comment on this issue
