### ISSUE TITLE
having issues please fix the pubspec

### ISSUE THREAD

**Issue by fisforfaheem** [gabrielpatricksouza/image_network#18]
Because image_network 2.5.2 depends on http >=0.13.4 <1.0.0 and no versions of image_network match >2.5.2 <3.0.0, image_network ^2.5.2 requires http >=0.13.4 <1.0.0.
So, because admin depends on both http ^1.0.0 and image_network ^2.5.2, version solving failed.
exit code 1

also please run flutter pub upgrade once in terminal

**Comment by gabrielpatricksouza** [comment]
Bug fixed in version: 2.5.3+1.
Thank you for your comment.
