### ISSUE TITLE
flutter web

### ISSUE THREAD

**Issue by jaish702** [gabrielpatricksouza/image_network#2]
Performing hot restart...                                          693ms
329294fd] may not be set.
Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [_iframe_6b9f6873_43c9_46db_bd0f_2085329294fd] may not be set.   
Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.
√ The page has finished loading!

**Comment by gabrielpatricksouza** [comment]
Thank you very much for your message. This issue has been resolved and is now available as of version ^2.4.0.
