### ISSUE TITLE
 platformViewRegistry getter is deprecated

### ISSUE THREAD

**Issue by Zeebzog** [gabrielpatricksouza/image_network#21]
Hi,

This package as been extremely useful so I hope the following can be addressed. I am getting the following warning when using:

ImageNetwork

'The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.'

Is it possible to address this?

Thank you.

**Comment by KoustuvGanguly** [comment]
Same here.
