### ISSUE TITLE
scroll issue

### ISSUE THREAD

**Issue by harithwick** [gabrielpatricksouza/image_network#7]
When the cursor is on top of the imagenetwork widget I cant scroll on web.

**Comment by harithwick** [comment]
Hope this helps someone. You can fix this by adding ignoreAllGestures: true, under the WebViewX widget in file image_network.dart

**Comment by gabrielpatricksouza** [comment]
Hello my friend, thank you very much for the report. Sorry for the delay, I was looking for a way to fix it without impacting other features, and this is already available as of [v2.5.1]

(https://pub.dev/packages/image_network/versions/2.5.1)
